const mongoose  = require("mongoose");

const akun = new mongoose.Schema({
    username : String,
    password : String,
    nama : String
  });
  
  
  const form_data = new mongoose.Schema({
    nama:String,
    nomer_telephone:String,
    jam:String
  });
  
  const db_atur_img = new mongoose.Schema({
    img_slide:{
        img_satu:String,
        img_satu_tulisan:{ 
            judulproduk:String,
            deskripsi:String
        },
        img_dua:String,
        img_dua_tulisan:{ 
            judulproduk:String,
            deskripsi:String
        },
        img_tiga:String,
        img_tiga_tulisan:{ 
            judulproduk:String,
            deskripsi:String
        },
        img_empat:String,
        img_empat_tulisan:{ 
            judulproduk:String,
            deskripsi:String
        },
        img_lima:String,
        img_lima_tulisan:{ 
            judulproduk:String,
            deskripsi:String
        }

    },
    judul_dan_deskripsi_produk:{
        judul:String,
        jenis_produk:String,
        deskripsi_produk:String
    },
    filter:{
        satu:String,
        dua:String,
        tiga:String,
        empat:String,
        lima:String,
        enam:String
    },
    all_img:{
        img_satu:{
            img:String,
            judulproduk:String,
            deskripsiproduk:String,
            filter:String
        },
        img_dua:{
            img:String,
            judulproduk:String,
            deskripsiproduk:String,
            filter:String
        },
        img_tiga:{
            img:String,
            judulproduk:String,
            deskripsiproduk:String,
            filter:String
        },
        img_empat:{
            img:String,
            judulproduk:String,
            deskripsiproduk:String,
            filter:String
        },
        img_lima:{
            img:String,
            judulproduk:String,
            deskripsiproduk:String,
            filter:String
        },
        img_enam:{
            img:String,
            judulproduk:String,
            deskripsiproduk:String,
            filter:String
        },
        img_tuju:{
            img:String,
            judulproduk:String,
            deskripsiproduk:String,
            filter:String
        },
        img_lapan:{
            img:String,
            judulproduk:String,
            deskripsiproduk:String,
            filter:String
        },
        img_sembilan:{
            img:String,
            judulproduk:String,
            deskripsiproduk:String,
            filter:String
        },
        img_sepuluh:{
            img:String,
            judulproduk:String,
            deskripsiproduk:String,
            filter:String
        },
        img_sebelas:{
            img:String,
            judulproduk:String,
            deskripsiproduk:String,
            filter:String
        },
        img_duabelas:{
            img:String,
            judulproduk:String,
            deskripsiproduk:String,
            filter:String
        },
        img_tigabelas:{
            img:String,
            judulproduk:String,
            deskripsiproduk:String,
            filter:String
        },
        img_empatbelas:{
            img:String,
            judulproduk:String,
            deskripsiproduk:String,
            filter:String
        },
        img_limabelas:{
            img:String,
            judulproduk:String,
            deskripsiproduk:String,
            filter:String
        },
        img_enambelas:{
            img:String,
            judulproduk:String,
            deskripsiproduk:String,
            filter:String
        },
        img_tujubelas:{
            img:String,
            judulproduk:String,
            deskripsiproduk:String,
            filter:String
        },
        img_lapanbelas:{
            img:String,
            judulproduk:String,
            deskripsiproduk:String,
            filter:String
        },
        img_sembilanbelas:{
            img:String,
            judulproduk:String,
            deskripsiproduk:String,
            filter:String
        },
        img_duapuluh:{
            img:String,
            judulproduk:String,
            deskripsiproduk:String,
            filter:String
        }
    }
  });

  module.exports = {
    data_akun:mongoose.model('akun_violets', akun),
    data_form_data:mongoose.model('form_datas',form_data),
    db_atur_img:mongoose.model('ab_atur_img',db_atur_img)
}